### ISSUE TITLE
Bike share dock locations should be cached

### ISSUE THREAD

**Issue by rfilmyer** [shalperin/PhillyBikeShare-Android#6]
I don't have a data plan on my phone, so if I'm not around wifi when I'm biking I can't tell where stations are (the pins don't appear on the map).  
Instead, there should be a fallback so that you can at least see where a station is on the map, and maybe get its location (which is usually precached as well).

**Comment by billyf** [comment]
Hey @rfilmyer - I created a fork to help with your request. It displays the previous kiosk results when you don't have data access. Let me know if you try it out!
